const Data = {
  productItems: [
    {
      id: 1,
      titile: "samsung glaxy",
      cover: "./images/flash/flash-1.png",
      name: "Shoes",
      price: 4000,
      bids: 4,
      time: "4d 10h",
    },
    {
      id: 2,
      titile: "samsung glaxy",
      cover: "./images/flash/flash-1.png",
      name: "Shoes",
      price: 4000,
      bids: 4,
      time: "4d 10h",
    },
    {
      id: 3,
      titile: "samsung glaxy",
      cover: "./images/flash/flash-1.png",
      name: "Shoes",
      price: 4000,
      bids: 4,
      time: "4d 10h",
    },
    {
      id: 4,
      titile: "samsung glaxy",
      cover: "./images/flash/flash-1.png",
      name: "Shoes",
      price: 4000,
      bids: 4,
      time: "4d 10h",
    },
    {
      id: 5,
      titile: "samsung glaxy",
      cover: "./images/flash/flash-1.png",
      name: "Shoes",
      price: 4000,
      bids: 4,
      time: "4d 10h",
    },
    {
      id: 6,
      titile: "samsung glaxy",
      cover: "./images/flash/flash-1.png",
      name: "Shoes",
      price: 4000,
      bids: 4,
      time: "4d 10h",
    },
    {
      id: 7,
      titile: "samsung glaxy",
      cover: "./images/flash/flash-1.png",
      name: "Shoes",
      price: 4000,
      bids: 4,
      time: "4d 10h",
    },
    {
      id: 8,
      titile: "samsung glaxy",
      cover: "./images/flash/flash-1.png",
      name: "Shoes",
      price: 4000,
      bids: 4,
      time: "4d 10h",
    },
    {
      id: 9,
      titile: "samsung glaxy",
      cover: "./images/flash/flash-1.png",
      name: "Shoes",
      price: 4000,
      bids: 4,
      time: "4d 10h",
    },
  ],
};
export default Data;
